language: php

# faster builds on docker-container setup
sudo: false

# used for HHVM
addons:
  apt:
    packages:
      - tidy

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache
        - node_modules
        - $HOME/.cache/bower
        - $HOME/.npm

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

node_js:
    - "5"

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
    fast_finish: true
    exclude:
        - php: hhvm
          env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    allow_failures:
        - php: hhvm
    include:
        - php: 5.5
          env: BUILD_ASSETS="no"
        - php: 5.6
          env: BUILD_ASSETS="no"
        - php: hhvm
          env: BUILD_ASSETS="no"

# exclude v1 branches
branches:
    except:
        - master
        - dev

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update --no-progress
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;
    - if [[ "$BUILD_ASSETS" != "no" ]]; then source ~/.nvm/nvm.sh && nvm install 5.0; fi;
    - if [[ "$BUILD_ASSETS" != "no" ]]; then npm install -g npm@latest; fi;

script:
    - travis_wait composer update --no-interaction --no-progress
    - ant prepare-$DB
    - bin/phpunit -v
